(deftheme xj-sealing
  "Created 2020-02-19.")

(custom-theme-set-faces
 'xj-sealing
 '(cursor ((t (:background "#f7ff5a"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#37afff"))))
 '(homoglyph ((t (:foreground "#00c5c7"))))
 '(minibuffer-prompt ((t (:foreground "DeepPink1"))))
 '(highlight ((t (:background "gray43" :foreground "turquoise1"))))
 '(region ((t (:background "#3E4451"))))
 '(shadow ((t (:foreground "SkyBlue4"))))
 '(secondary-selection ((t (:background "#121417"))))
 '(trailing-whitespace ((t (:background "tomato1"))))
 '(font-lock-builtin-face ((t (:foreground "deep pink" :weight semi-bold))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "LightSkyBlue4" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "Cyan"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#1dd8ff"))))
 '(font-lock-keyword-face ((t (:foreground "#ff04f7" :slant italic))))
 '(font-lock-negation-char-face ((t (:foreground "#56B6C2"))))
 '(font-lock-preprocessor-face ((t (:foreground "#828997"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "green1"))))
 '(font-lock-type-face ((t (:foreground "#f7ff5a"))))
 '(font-lock-variable-name-face ((t (:foreground "IndianRed1" :weight semi-light))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#5C6370"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#61AFEF"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#61AFEF"))))
 '(fringe ((t (:background "#0d0e17"))))
 '(header-line ((t (:background "#21252B"))))
 '(tooltip ((t (:inherit variable-pitch :background "#121417" :foreground "#ABB2BF"))))
 '(mode-line ((t (:background "#21252B" :foreground "#9DA5B4" :box (:line-width 1 :color "#181A1F")))))
 '(mode-line-buffer-id ((t (:foreground "#FFFFFF" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#181A1F") :foreground "#3E4451" :background "#181A1F"))))
 '(isearch ((t (:background "#C678DD" :foreground "#282C34"))))
 '(isearch-fail ((t (:foreground "#BE5046"))))
 '(lazy-highlight ((t (:background "#121417" :foreground "#C678DD" :underline "#C678DD"))))
 '(match ((t (:background "RoyalBlue3"))))
 '(next-error ((t (:inherit region))))
 '(query-replace ((t (:inherit isearch))))
 '(diff-hl-change ((t (:foreground "#E9C062" :background "#8b733a"))))
 '(diff-hl-delete ((t (:foreground "#CC6666" :background "#7a3d3d"))))
 '(diff-hl-insert ((t (:foreground "#A8FF60" :background "#547f30"))))
 '(default ((t (:inherit nil :stipple nil :background "#0d0e17" :foreground "SlateGray1" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 105 :width normal :foundry "nil" :family "Menlo")))))

(provide-theme 'xj-sealing)
